config/routes.rb
Rails.application.routes.draw do
  root to: 'publications#index'
  devise_for :users
  resources  :users, except: %i[new index]
  resources  :publications, only: %i[index show new create]
  resources  :likes, only: %i[create destroy]
  resources  :comments, only: [:create]
  resources  :friendships, only: %i[create destroy]
  resources  :notifications, only: [:destroy]
  resources  :messages, only: %i[new create]
  resources  :chats, only: %i[index show]
  post '/users/:id/set_avatar', to: 'users#set_avatar'
  delete '/users/:id/remove_avatar', to: 'users#remove_avatar'
  post '/publications/add_publication', to: 'publications#add_publication'
  get '/publications/:user_id/get_user_publication/:pub_id', to: 'publications#get_user_publication'
  get '/search_user', to: 'users#search_by_login_or_name'
  mount ActionCable.server => '/cable'
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user

  has_many_attached :photos

  has_many :likes, as: :likeable

  has_many :comments

  validates :description, presence: true
end

app/controllers/publications_controller.rb
# frozen_string_literal: true

class PublicationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_publication, only: %i[show like add_comment]

  def index
    @publications = Publication.all.order(created_at: :desc).with_attached_photos
  end

  def show
    @user = @publication.user
    respond_to do |format|
      format.js
      format.html { render_404 }
    end
  end

  def new
    respond_to do |format|
      format.js
      format.html { render_404 }
    end
  end

  def create
    @publication = current_user.publications.new(description: params[:description])
    params[:photo]&.each do |photo|
      @publication.photos.attach(photo)
    end
    @publication.save
  end

  def get_user_publication
    @user = User.find(params[:user_id])
    @publication = @user.publications.find(params[:pub_id])
    @next_pub = next_publication(@user, @publication)
    @previous_pub = previous_publication(@user, @publication)

    respond_to do |format|
      format.js
      format.html { render_404 }
    end
  end

  private

  def find_publication
    @publication = Publication.find_by(id: params[:id])
    render_404 unless @publication
  end

  def previous_publication(user, publication)
    user.publications.where('id > ?', publication.id).first
  end

  def next_publication(user, publication)
    user.publications.where('id < ?', publication.id).last
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/get_user_publication.js.erb
$('.modal-backdrop').remove();
$("#place-for-modal").html("<%= j (render partial: 'partial/show_publication') %>");
$("#showPublicationModal").modal('toggle');

app/views/publications/index.html.haml
.container.mt-4
  .row
    .publication-main-column
      - @publications.each do |pub|
      - @user = pub.user
        .publication-content-container
          .publication-author-credentials
            = link_to user_path(@user.id), class: "publication-avatar-container" do
              - if @user.avatar.attached?
                = image_tag @user.avatar, class: "publication-avatar"
              - else
                = svg "user_icon_glyph"
            .publication-info
              %div 
                = @user.login
              %div 
                = pub.created_at
          - if !pub.photos.empty?
            = link_to publication_path(pub.id), remote: true do 
              .publication-preview{style: "background: url('#{ url_for(pub.photos[0]) }') center no-repeat; background-size: cover;"}
          .publication-footer
            .publication-actions-bar
              .publication-action-button{id: "like-pub-button-#{pub.id}" }
                - like = pub.likes.find { |like| like.user_id == current_user.id }
                = render partial: 'partial/like_button', locals: { like: like, publication: pub }
              = link_to publication_path(pub.id), class: "publication-action-button", method: :get, remote: true do 
                = svg "message_icon"
            - if !pub.description.nil? && !pub.description.empty?
              .publication-description
                %b 
                  = @user.login + ": "
                = pub.description

app/views/publications/new.js.erb
$('.modal-backdrop').remove();
$("#place-for-modal").html("<%= j (render partial: 'partial/add_publication') %>");
$("#addPublicationModal").modal('toggle');

app/views/publications/show.js.erb
$("#place-for-modal").html("<%= j (render partial: 'partial/show_publication') %>")
$("#showPublicationModal").modal('show');