config/routes.rb
Rails.application.routes.draw do
  root to: 'publications#index'
  devise_for :users
  resources  :users, except: %i[new index]
  resources  :publications, only: %i[index show new create]
  resources  :likes, only: %i[create destroy]
  resources  :comments, only: [:create]
  resources  :friendships, only: %i[create destroy]
  resources  :notifications, only: [:destroy]
  resources  :messages, only: %i[new create]
  resources  :chats, only: %i[index show]
  post '/users/:id/set_avatar', to: 'users#set_avatar'
  delete '/users/:id/remove_avatar', to: 'users#remove_avatar'
  post '/publications/add_publication', to: 'publications#add_publication'
  get '/publications/:user_id/get_user_publication/:pub_id', to: 'publications#get_user_publication'
  get '/search_user', to: 'users#search_by_login_or_name'
  mount ActionCable.server => '/cable'
end

app/models/user.rb
require 'elasticsearch/model'

class User < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  include Rails.application.routes.url_helpers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :publications

  has_one_attached :avatar

  validates :email, uniqueness: true
  validates :login, uniqueness: true

  has_many :likes

  has_many :comments

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :notifications

  has_many :outbox_chats, class_name: 'Chat', foreign_key: :starter_id
  has_many :interlocutors, through: :outbox_chats
  has_many :inbox_chats, class_name: 'Chat', foreign_key: :interlocutor_id
  has_many :starters, through: :inbox_messages

  has_many :messages, foreign_key: :sender_id

  def follows?(id)
    return true if friends.find_by(id: id)

    false
  end

  def followed_by?(id)
    return true if inverse_friends.find_by(id: id)

    false
  end
end

# User.__elasticsearch__.create_index!
# User.import

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Rails.application.routes.url_helpers

  before_action :authenticate_user!, only: %i[index edit update destroy set_avatar remove_avatar]
  before_action :find_user, only: %i[show edit update destroy set_avatar remove_avatar]
  before_action :permit_only_current_user, only: %i[edit destroy set_avatar remove_avatar]

  def index
    @users = User.all
  end

  def show
    @publications = @user.publications.order(created_at: :desc)
    return unless user_signed_in? && @user.id == current_user.id

    @avatar_props = {
      user_id: @user.id,
      action: 'show'
    }
  end

  def edit
    @user_props = {
      user_id: @user.id,
      login: @user.login,
      name: @user.name,
      email: @user.email,
      web_page: @user.web_page,
      phone: @user.phone,
      gender: @user.gender,
      about_me: @user.about_me
    }
  end

  def update
    @user.update(user_params)
    return unless @user.errors.empty?

    flash[:success] = 'your profile settings have been updated'
    render json: {}
  end

  def destroy; end

  def set_avatar
    Rails.logger.debug params.inspect
    @user.avatar.attach(params[:avatar])

    render json: {
      avatar_url: rails_blob_path(
        @user.avatar,
        disposition: 'attachment',
        only_path: true
      )
    }
  end

  def remove_avatar
    @user.avatar.purge
    render json: {}
  end

  def search_by_login_or_name
    @users = User.__elasticsearch__.search(
      query: {
        multi_match: {
          query: params[:login],
          fields: %w[name login]
        }
      }
    ).records.to_a
    respond_to do |format|
      format.js
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    render_404 unless @user
  end

  def permit_only_current_user
    render_403 unless @user.id == current_user.id
  end

  def user_params
    params.require(:user).permit(:name,
                                 :login,
                                 :email,
                                 :web_page,
                                 :about_me,
                                 :phone,
                                 :gender)
  end

  def avatar_url(user)
    if user.avatar.attached?
      url_for(@user.avatar)
    else
      false
    end
  end

  def authenticity_token
    session[:_csrf_token] ||= SecureRandom.base64(32)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= react_component("UserEdit", props: @user_props, prerender: false)

app/views/users/search_by_login_or_name.js.erb
<% if @users.length > 0 %>
  $(".navbar-search-results").css('display', 'block');
  $(".navbar-search-results").html("<%= j (render partial: 'partial/user_search_result' , locals: { users: @users }) %>");
<% end %>

app/views/users/show.html.haml
.container
  .user-credentials-container
    .col
      - if user_signed_in? && @user.id == current_user.id 
        = react_component("UserShowAvatarContainer", props: @avatar_props, prerender: false)
      - else
        .user-avatar-container
          - if @user.avatar.attached?
            = image_tag @user.avatar, class: "avatar avatar-big"
          - else
            = svg 'user_icon_glyph'
    .col
      .user-credentials-row
        .user-login
          = @user.login
        - if user_signed_in? && @user.id == current_user.id
          = link_to  edit_user_path, class: "user-edit-button" do
            Edit profile
      .user-credentials-row{ id: 'userMetrics' }
        = render partial: 'partial/user_metrics', locals: { user: @user }
      %p.user-name
        = @user.name
      .user-friendship
        - if user_signed_in? && @user.id != current_user.id
          = render partial: 'partial/user_friendship',locals: { user: @user }
      - if user_signed_in? && @user.id != current_user.id
        = link_to new_message_path({ recipient_id: @user.id }), remote: true do
          .btn.btn-primary
            Send message
  .user-publications-container
    - @publications.each do |pub|
      = link_to "/publications/#{@user.id}/get_user_publication/#{pub.id}", remote: true do
        .user-publication-preview{style: "background: url('#{url_for(pub.photos[0]) }') center no-repeat; background-size: cover;"}





        