config/routes.rb
Rails.application.routes.draw do
  root to: 'publications#index'
  devise_for :users
  resources  :users, except: %i[new index]
  resources  :publications, only: %i[index show new create]
  resources  :likes, only: %i[create destroy]
  resources  :comments, only: [:create]
  resources  :friendships, only: %i[create destroy]
  resources  :notifications, only: [:destroy]
  resources  :messages, only: %i[new create]
  resources  :chats, only: %i[index show]
  post '/users/:id/set_avatar', to: 'users#set_avatar'
  delete '/users/:id/remove_avatar', to: 'users#remove_avatar'
  post '/publications/add_publication', to: 'publications#add_publication'
  get '/publications/:user_id/get_user_publication/:pub_id', to: 'publications#get_user_publication'
  get '/search_user', to: 'users#search_by_login_or_name'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :starter, class_name: 'User'
  belongs_to :interlocutor, class_name: 'User'
  has_many :messages
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :chat

  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user

  has_many_attached :photos

  has_many :likes, as: :likeable

  has_many :comments

  validates :description, presence: true
end

app/models/user.rb
require 'elasticsearch/model'

class User < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  include Rails.application.routes.url_helpers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :publications

  has_one_attached :avatar

  validates :email, uniqueness: true
  validates :login, uniqueness: true

  has_many :likes

  has_many :comments

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: :friend_id
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :notifications

  has_many :outbox_chats, class_name: 'Chat', foreign_key: :starter_id
  has_many :interlocutors, through: :outbox_chats
  has_many :inbox_chats, class_name: 'Chat', foreign_key: :interlocutor_id
  has_many :starters, through: :inbox_messages

  has_many :messages, foreign_key: :sender_id

  def follows?(id)
    return true if friends.find_by(id: id)

    false
  end

  def followed_by?(id)
    return true if inverse_friends.find_by(id: id)

    false
  end
end

# User.__elasticsearch__.create_index!
# User.import

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def index
    @chats = []
    @chats.concat(current_user.inbox_chats).to_a
    @chats.concat(current_user.outbox_chats).to_a
  end

  def show
    render_404 unless (@chat = Chat.find_by(id: params[:id]))
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    if like_params[:likeable_type] == 'Publication'
      @publication = Publication.find_by(id: like_params[:likeable_id])
      @like = @publication.likes.create(user_id: current_user.id)
    end

    respond_to do |format|
      format.js
      format.html { render_404 }
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    if @like.likeable_type == 'Publication'
      @publication = Publication.find_by(id: @like.likeable_id)
      @publication.likes.destroy(@like)
    end

    respond_to do |format|
      format.js
      format.html { render_404 }
    end
  end

  private

  def like_params
    params.permit(:likeable_id, :likeable_type)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Rails.application.routes.url_helpers

  before_action :authenticate_user!, only: %i[index edit update destroy set_avatar remove_avatar]
  before_action :find_user, only: %i[show edit update destroy set_avatar remove_avatar]
  before_action :permit_only_current_user, only: %i[edit destroy set_avatar remove_avatar]

  def index
    @users = User.all
  end

  def show
    @publications = @user.publications.order(created_at: :desc)
    return unless user_signed_in? && @user.id == current_user.id

    @avatar_props = {
      user_id: @user.id,
      action: 'show'
    }
  end

  def edit
    @user_props = {
      user_id: @user.id,
      login: @user.login,
      name: @user.name,
      email: @user.email,
      web_page: @user.web_page,
      phone: @user.phone,
      gender: @user.gender,
      about_me: @user.about_me
    }
  end

  def update
    @user.update(user_params)
    return unless @user.errors.empty?

    flash[:success] = 'your profile settings have been updated'
    render json: {}
  end

  def destroy; end

  def set_avatar
    Rails.logger.debug params.inspect
    @user.avatar.attach(params[:avatar])

    render json: {
      avatar_url: rails_blob_path(
        @user.avatar,
        disposition: 'attachment',
        only_path: true
      )
    }
  end

  def remove_avatar
    @user.avatar.purge
    render json: {}
  end

  def search_by_login_or_name
    @users = User.__elasticsearch__.search(
      query: {
        multi_match: {
          query: params[:login],
          fields: %w[name login]
        }
      }
    ).records.to_a
    respond_to do |format|
      format.js
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    render_404 unless @user
  end

  def permit_only_current_user
    render_403 unless @user.id == current_user.id
  end

  def user_params
    params.require(:user).permit(:name,
                                 :login,
                                 :email,
                                 :web_page,
                                 :about_me,
                                 :phone,
                                 :gender)
  end

  def avatar_url(user)
    if user.avatar.attached?
      url_for(@user.avatar)
    else
      false
    end
  end

  def authenticity_token
    session[:_csrf_token] ||= SecureRandom.base64(32)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg(name)
    file_path = "#{Rails.root}/app/assets/images/#{name}.svg"
    return File.read(file_path).html_safe if File.exist?(file_path)

    '(not found)'
  end

  def user_profile_path?
    params[:controller] == 'users' && params[:action] == 'show'
  end

  def get_avatar_url(user)
    avatar = if user.avatar.attached?
               url_for(user.avatar)
             else
               false
             end
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title JDIgram
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'jdigram-bundle'
   
  %body.bg-light
    - if user_signed_in?
      = react_component("InitialContainer", props: {avatar: get_avatar_url(current_user)}, prerender: true)
    - if user_signed_in? || user_profile_path?
      = render partial: "partial/navbar"
    .flash-info
      = flash[:success]
    = yield
    #place-for-modal

app/views/partial/_add_publication.html.haml
.container
  .modal.fade{ id: "addPublicationModal", tabindex: -1, aria: { hidden: true } }
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title
            Share your impressions
          %button.btn-close{data: {bs: {dismiss: "modal"}}}
        .modal-body
          .container
            .pub-avatar-description-row
              .pub-avatar-container
                - if current_user.avatar.attached?
                  = image_tag current_user.avatar, class: "pub-avatar"
                - else
                  = svg "user_icon_glyph"
              %textarea.pub-description
            .pub-photo-list
        .pub-footer
          %label.pub-add-photo{for: "photo_input"}
            %input.pub-photo-input{type: "file", id: "photo_input", accept: "image/*", multiple: true}
            = svg "add_photo"
          %button.btn.btn-primary{id: "addPublicationButton"}
            Save

app/views/partial/_chat_message.html.haml
.chat-message-row
  = link_to user_path(message.sender), class: "chat-avatar-container" do
    - if message.sender.avatar.attached?
      = image_tag url_for(message.sender.avatar), class: "chat-avatar"
    - else
      = svg "user_icon_glyph"
  .w-75
    .chat-message-sender-login
      = message.sender.login
    .chat-message-text
      = message.text

app/views/partial/_comment.html.haml
.pub-show-comment-row
  .pub-show-avatar-container
    - if comment.user.avatar.attached?
      = image_tag comment.user.avatar, class: "pub-show-avatar"
    - else
      = svg "user_icon_glyph"
  .pub-show-description-block
    .pub-show-author-login
      = comment.user.login
    .pub-show-description
      = comment.text

app/views/partial/_like_button.html.haml
- if like
  = link_to like_path(like.id), method: :delete, remote: true do 
    = svg "heart_icon_filled"
- else
  = link_to likes_path({ likeable_id: publication.id, likeable_type: 'Publication' }),  method: :post, remote: true  do 
    = svg "heart_icon"

app/views/partial/_navbar.html.haml
.navbar-container
  .navbar-logo
    JDIgram
  .col.d-flex.align-items-center
    - if user_signed_in?
      %input.navbar-user-search
        .navbar-search-results
    .navbar-search-clear-button
  .navbar-buttons-row
    - if user_signed_in?
      .navbar-navigation-buttons
        = link_to publications_path, class: "navbar-button me-1" do
          = svg 'home_icon'
        .navbar-button.me-1
          = link_to chats_path do 
            = svg "message_icon"
        .navbar-button.me-1
          = svg "heart_icon"
        .navbar-button.navbar-notification.me-1
          = render partial: 'partial/navbar_notifications'
        %button.navbar-menu.navbar-button.me-1
          = react_component("NavbarAvatarContainer", props: {})
          .navbar-menu-popup
            = link_to user_path(current_user.id), class: "navbar-menu-popup-item" do
              .navbar-menu-popup-image
                = svg "user_icon" 
              .navbar-menu-popup-description
                Profile
            = link_to new_publication_path, class: 'navbar-menu-popup-item', remote: true do
              .navbar-menu-popup-image
                = svg "add_publication"
              .navbar-menu-popup-description
                Add a publication
            = link_to edit_user_path(current_user.id), class: "navbar-menu-popup-item border-bottom" do
              .navbar-menu-popup-image
                = svg "user_settings_icon"
              .navbar-menu-popup-description
                Prefences
            = link_to destroy_user_session_url, method: :delete, class: "navbar-menu-popup-item" do
              .navbar-menu-popup-description
                Sign out
    - else 
      = link_to new_user_session_path, class: "btn btn-primary" do 
        Sign in 
      = link_to new_user_registration_path do
        Sign up
            

app/views/partial/_navbar_notifications.html.haml
- if current_user.notifications.empty?
  = svg "bell_icon"
  .navbar-notification-popup
    You have no notifications
- else
  = svg "bell_alarm_icon"
  .navbar-notification-popup
    - current_user.notifications.reverse.each do |notification|
      - @sender = User.find_by(id: notification.sender_id)
      .navbar-notification-popup-item
        .navbar-notification-popup-text
          - case notification.status
            - when "Subscribed"
              User 
              = link_to user_path(@sender) do
                = @sender.login
              is subscribed to you
              - if !current_user.follows?(@sender)
                .navbar-notification-popup-actions
                  = link_to friendships_path({ friend_id: @sender.id }), method: :post, remote: true do
                    subscribe in response?                    
            - when "Unsubscribed"
              User
              = link_to user_path(@sender) do
                = @sender.login
              canceled his subscription

        = link_to notification_path(notification), method: :delete, remote: true do
          .btn.btn-close
:javascript

  $(".navbar-notification").click(function() {
    if ($(".navbar-notification-popup").css('display') == 'none') {
      $(".navbar-notification-popup").show();
    } else {
      $(".navbar-notification-popup").hide();
    }
  });


        

app/views/partial/_new_message.html.haml
.container
  .modal.fade{ id: "newMessageModal", tabindex: -1, aria: { hidden: true } }
    .modal-dialog
      .modal-content
        .modal-header
          %h5.modal-title
            New message
          %button.btn-close{data: {bs: {dismiss: "modal"}}}
        .modal-body
          .message-recipient-credentials
            .message-avatar-container
              - if @recipient.avatar.attached?
                = image_tag @recipient.avatar, class: "message-avatar"
              - else
                = svg "user_icon_glyph"
            %div
              .message-recipient-login
                = @recipient.login
              %div
              = @recipient.name
          = form_with url: messages_path, class: "message-form", remote: true do |form|
            = form.hidden_field :recipient_id, value: @recipient.id
            = form.text_area :text, class: "message-text"
            = form.submit 'Send', class: "message-submit"
        

app/views/partial/_photo_slider.html.haml
- if publication.photos.length < 2
  = image_tag publication.photos.first, width: '100%'
- else
  #carousel.carousel.slide{"data-bs-ride" => "carousel"}
    %ol.carousel-indicators
      %li.active{"data-bs-slide-to" => "0", "data-bs-target" => "#carousel"}
      - (publication.photos.length - 1).times do |i|
        %li{"data-bs-slide-to" => i + 1, "data-bs-target" => "#carousel"}
    .carousel-inner                      
      .carousel-item.active
        = image_tag publication.photos.first, {class: "d-block w-100"}
      - publication.photos.drop(1).each do |photo|
        .carousel-item
          = image_tag photo, {class: "d-block w-100"}

    %button.carousel-control-prev{"data-bs-target" => "#carousel", "data-bs-slide" => "prev"}
      %span.carousel-control-prev-icon
    %button.carousel-control-next{"data-bs-target" => "#carousel", "data-bs-slide" => "next"}
      %span.carousel-control-next-icon

app/views/partial/_show_publication.html.haml
.modal.fade{ id: "showPublicationModal", tabindex: -1, aria: { hidden: true } }
  .pub-show-close-container
    %button.button.pub-show-close{ data: { bs: { dismiss: "modal" } } }

  .modal-dialog.modal-lg
    .modal-content
      .modal-body.pub-show-body

        - if @previous_pub
          = link_to "/publications/#{@user.id}/get_user_publication/#{@previous_pub.id}", class: "pub-show-publication-previous", remote: true do
            .pub-show-left-arrow
          
        .pub-show-content
          .pub-show-photo-column
            .pub-show-photo
              - if @publication.photos.length > 0
                = render partial: "partial/photo_slider", locals: {publication: @publication}
              - else
                = svg "photo_icon_light"
          .pub-author-credentials
            .pub-show-avatar-container
              - if @user.avatar.attached?
                = image_tag @user.avatar, class: "pub-show-avatar"
              - else
                = svg "user_icon_glyph"
            .pub-show-author-login
              = @user.login  
          .pub-show-info       
            .pub-show-description-container
              .pub-show-avatar-container
                - if @user.avatar.attached?
                  = image_tag @user.avatar, class: "pub-show-avatar"
                - else
                  = svg "user_icon_glyph"
              .pub-show-description-block
                .pub-show-author-login
                  = @user.login 
                .pub-show-description
                  = @publication.description

            .pub-show-comments
              - @publication.comments.each do |comment|
                = render partial: "partial/comment", locals: {user: comment.user, comment: comment }

            .pub-show-actions-bar
              .publication-action-button{id: "like-pub-button" }
                - like = @publication.likes.find { |like| like.user_id == current_user.id }
                = render partial: 'partial/like_button', locals: { like: like, publication: @publication }

            = form_with url: comments_path, class: "pub-show-add-comment-row", method: :post, remote: true do |form|
              = form.hidden_field :pub_id, value: @publication.id
              = form.text_area :text, placeholder: "Write something!", class: "pub-show-add-comment-text"
              = form.submit "Send", class: "pub-show-submit"
        - if @next_pub
          = link_to "/publications/#{@user.id}/get_user_publication/#{@next_pub.id}", class: "pub-show-publication-next", remote: true do
            .pub-show-right-arrow

app/views/partial/_user_friendship.html.haml
- if current_user.followed_by?(user)
  - if current_user.follows?(user)
    Uou are subscribed to each other,
    = link_to friendship_path(current_user.friendships.find_by(friend_id: user.id)), method: :delete, remote: true do
      unsubscribe?
  - else
    User is subscribed to you, 
    = link_to friendships_path({ friend_id: user.id }), method: :post, remote: true do
      subscribe in response?
- elsif current_user.follows?(user)
  you are subscribed,
  = link_to friendship_path(current_user.friendships.find_by(friend_id: user.id)), method: :delete, remote: true do
    unsubscribe?
- else
  You are not subscribed,
  = link_to friendships_path({ friend_id: user.id }), method: :post, remote: true do
    subscribe?

app/views/partial/_user_metrics.html.haml
%p.user-metrics-counter
  = user.publications.count
  publications
%p.user-metrics-counter
  = user.inverse_friends.count
  followers
%p.user-metrics-counter
  = user.friends.count 
  following

app/views/partial/_user_search_result.html.haml
- users.each do |user|
  = link_to user_path(user.id), class: "navbar-search-result-item" do
    .navbar-avatar-container
      - if user.avatar.attached?
        = image_tag user.avatar, class: "navbar-avatar"
      - else
        = svg "user_icon_glyph"
    %div
      %div
        = user.login
      %div
        = user.name