config/routes.rb
Rails.application.routes.draw do
  root to: 'publications#index'
  devise_for :users
  resources  :users, except: %i[new index]
  resources  :publications, only: %i[index show new create]
  resources  :likes, only: %i[create destroy]
  resources  :comments, only: [:create]
  resources  :friendships, only: %i[create destroy]
  resources  :notifications, only: [:destroy]
  resources  :messages, only: %i[new create]
  resources  :chats, only: %i[index show]
  post '/users/:id/set_avatar', to: 'users#set_avatar'
  delete '/users/:id/remove_avatar', to: 'users#remove_avatar'
  post '/publications/add_publication', to: 'publications#add_publication'
  get '/publications/:user_id/get_user_publication/:pub_id', to: 'publications#get_user_publication'
  get '/search_user', to: 'users#search_by_login_or_name'
  mount ActionCable.server => '/cable'
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :starter, class_name: 'User'
  belongs_to :interlocutor, class_name: 'User'
  has_many :messages
end

app/controllers/chats_controller.rb
# frozen_string_literal: true

class ChatsController < ApplicationController
  def index
    @chats = []
    @chats.concat(current_user.inbox_chats).to_a
    @chats.concat(current_user.outbox_chats).to_a
  end

  def show
    render_404 unless (@chat = Chat.find_by(id: params[:id]))
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/index.html.haml
.container.chat-container
  - if !@chats.empty?
    - @chats.each do |chat|
      = link_to chat_path(chat), class: "chat-row" do  
        - if chat.starter.id == current_user.id
          - interlocutor = chat.interlocutor
        - else 
          - interlocutor = chat.starter
        .chat-avatar-container
          - if interlocutor.avatar.attached?
            = image_tag interlocutor.avatar, class: "chat-avatar"
          - else
            = svg "user_icon_glyph"
        %div
          %div.fw-bold
            = interlocutor.login
          %div
            - if chat.messages.last.sender.id == current_user.id
              You: 
              = chat.messages.last.text
            - else
              = chat.messages.last.text

app/views/chats/show.html.haml
.container.chat-container
  - if @chat.starter.id == current_user.id
    - interlocutor = @chat.interlocutor
  - else 
    - interlocutor = @chat.starter
  .chat-header
    = link_to chats_path, class: "btn btn-light" do
      < Back
    = interlocutor.login
    = link_to user_path(interlocutor), class: "chat-avatar-container" do
      - if interlocutor.avatar.attached?
        = image_tag interlocutor.avatar, class: "chat-avatar"
      - else
        = svg "user_icon_glyph"
  .chat-messages-container
    - @chat.messages.each do |message|
      = render partial: 'partial/chat_message', locals: { message: message }
  .chat-message-form
    %textarea.chat-message-field
    %button.chat-message-submit{ chat_id: @chat.id }
      Send